DROP TABLE IF EXISTS core_document_m;

CREATE TABLE core_document_m
(
    doc_id            VARCHAR(128) PRIMARY KEY NOT NULL,
    doc_name          VARCHAR(256)             NOT NULL,
    doc_type          VARCHAR(128)             NOT NULL,
    registration_code VARCHAR(32)              NOT NULL,
    country_state_id  VARCHAR(128)             NOT NULL,
    vehicle_type_id   VARCHAR(32)              NOT NULL,
    is_deleted        TINYINT                  NOT NULL DEFAULT False,
    created_by        BIGINT                   NOT NULL,
    created_time      TIMESTAMP                         DEFAULT NOW()
);

INSERT INTO core_document_m
(doc_id, doc_name, doc_type, registration_code, country_state_id, vehicle_type_id, is_deleted, created_by)
VALUES ('DOC_AP_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-AP', 'BIKE', 0, 0),
       ('DOC_AP_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-AP', 'BIKE', 0, 0),
       ('DOC_AP_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-AP', 'BIKE', 0, 0),
       ('DOC_AP_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-AP', 'BIKE', 0, 0),
       ('DOC_AP_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-AP', 'BIKE', 0, 0),
       ('DOC_AP_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-AP', 'CAR', 0, 0),
       ('DOC_AP_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-AP', 'CAR', 0, 0),
       ('DOC_AP_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-AP', 'CAR', 0, 0),
       ('DOC_AP_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-AP', 'CAR', 0, 0),
       ('DOC_AP_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-AP', 'CAR', 0, 0),
       ('DOC_AP_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-AP', 'SUV', 0, 0),
       ('DOC_AP_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-AP', 'SUV', 0, 0),
       ('DOC_AP_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-AP', 'SUV', 0, 0),
       ('DOC_AP_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-AP', 'SUV', 0, 0),
       ('DOC_AP_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-AP', 'SUV', 0, 0),
       ('DOC_AR_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-AR', 'BIKE', 0, 0),
       ('DOC_AR_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-AR', 'BIKE', 0, 0),
       ('DOC_AR_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-AR', 'BIKE', 0, 0),
       ('DOC_AR_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-AR', 'BIKE', 0, 0),
       ('DOC_AR_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-AR', 'BIKE', 0, 0),
       ('DOC_AR_BIKE_INNER_LINE_PERMIT___ILP_ARUNACHAL_PRADES_0901', 'Inner Line Permit - ILP (Arunachal Pradesh)', 'STATE_SPECIFIC', 'IN_STATE', 'IN-AR', 'BIKE', 0, 0),
       ('DOC_AR_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-AR', 'CAR', 0, 0),
       ('DOC_AR_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-AR', 'CAR', 0, 0),
       ('DOC_AR_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-AR', 'CAR', 0, 0),
       ('DOC_AR_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-AR', 'CAR', 0, 0),
       ('DOC_AR_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-AR', 'CAR', 0, 0),
       ('DOC_AR_CAR_INNER_LINE_PERMIT___ILP_ARUNACHAL_PRADES_0901', 'Inner Line Permit - ILP (Arunachal Pradesh)', 'STATE_SPECIFIC', 'IN_STATE', 'IN-AR', 'CAR', 0, 0),
       ('DOC_AR_CAR_PROTECTED_AREA_PERMIT_FOREIGN_NATIONALS__0902', 'Protected Area Permit (Foreign Nationals)', 'STATE_SPECIFIC', 'IN_STATE', 'IN-AR', 'CAR', 0, 0),
       ('DOC_AR_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-AR', 'SUV', 0, 0),
       ('DOC_AR_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-AR', 'SUV', 0, 0),
       ('DOC_AR_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-AR', 'SUV', 0, 0),
       ('DOC_AR_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-AR', 'SUV', 0, 0),
       ('DOC_AR_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-AR', 'SUV', 0, 0),
       ('DOC_AR_SUV_INNER_LINE_PERMIT___ILP_ARUNACHAL_PRADES_0901', 'Inner Line Permit - ILP (Arunachal Pradesh)', 'STATE_SPECIFIC', 'IN_STATE', 'IN-AR', 'SUV', 0, 0),
       ('DOC_AS_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-AS', 'BIKE', 0, 0),
       ('DOC_AS_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-AS', 'BIKE', 0, 0),
       ('DOC_AS_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-AS', 'BIKE', 0, 0),
       ('DOC_AS_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-AS', 'BIKE', 0, 0),
       ('DOC_AS_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-AS', 'BIKE', 0, 0),
       ('DOC_AS_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-AS', 'CAR', 0, 0),
       ('DOC_AS_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-AS', 'CAR', 0, 0),
       ('DOC_AS_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-AS', 'CAR', 0, 0),
       ('DOC_AS_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-AS', 'CAR', 0, 0),
       ('DOC_AS_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-AS', 'CAR', 0, 0),
       ('DOC_AS_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-AS', 'SUV', 0, 0),
       ('DOC_AS_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-AS', 'SUV', 0, 0),
       ('DOC_AS_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-AS', 'SUV', 0, 0),
       ('DOC_AS_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-AS', 'SUV', 0, 0),
       ('DOC_AS_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-AS', 'SUV', 0, 0),
       ('DOC_BR_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-BR', 'BIKE', 0, 0),
       ('DOC_BR_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-BR', 'BIKE', 0, 0),
       ('DOC_BR_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-BR', 'BIKE', 0, 0),
       ('DOC_BR_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-BR', 'BIKE', 0, 0),
       ('DOC_BR_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-BR', 'BIKE', 0, 0),
       ('DOC_BR_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-BR', 'CAR', 0, 0),
       ('DOC_BR_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-BR', 'CAR', 0, 0),
       ('DOC_BR_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-BR', 'CAR', 0, 0),
       ('DOC_BR_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-BR', 'CAR', 0, 0),
       ('DOC_BR_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-BR', 'CAR', 0, 0),
       ('DOC_BR_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-BR', 'SUV', 0, 0),
       ('DOC_BR_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-BR', 'SUV', 0, 0),
       ('DOC_BR_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-BR', 'SUV', 0, 0),
       ('DOC_BR_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-BR', 'SUV', 0, 0),
       ('DOC_BR_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-BR', 'SUV', 0, 0),
       ('DOC_CH_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-CH', 'BIKE', 0, 0),
       ('DOC_CH_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-CH', 'BIKE', 0, 0),
       ('DOC_CH_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-CH', 'BIKE', 0, 0),
       ('DOC_CH_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-CH', 'BIKE', 0, 0),
       ('DOC_CH_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-CH', 'BIKE', 0, 0),
       ('DOC_CH_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-CH', 'CAR', 0, 0),
       ('DOC_CH_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-CH', 'CAR', 0, 0),
       ('DOC_CH_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-CH', 'CAR', 0, 0),
       ('DOC_CH_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-CH', 'CAR', 0, 0),
       ('DOC_CH_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-CH', 'CAR', 0, 0),
       ('DOC_CH_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-CH', 'SUV', 0, 0),
       ('DOC_CH_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-CH', 'SUV', 0, 0),
       ('DOC_CH_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-CH', 'SUV', 0, 0),
       ('DOC_CH_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-CH', 'SUV', 0, 0),
       ('DOC_CH_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-CH', 'SUV', 0, 0),
       ('DOC_CT_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-CT', 'BIKE', 0, 0),
       ('DOC_CT_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-CT', 'BIKE', 0, 0),
       ('DOC_CT_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-CT', 'BIKE', 0, 0),
       ('DOC_CT_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-CT', 'BIKE', 0, 0),
       ('DOC_CT_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-CT', 'BIKE', 0, 0),
       ('DOC_CT_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-CT', 'CAR', 0, 0),
       ('DOC_CT_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-CT', 'CAR', 0, 0),
       ('DOC_CT_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-CT', 'CAR', 0, 0),
       ('DOC_CT_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-CT', 'CAR', 0, 0),
       ('DOC_CT_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-CT', 'CAR', 0, 0),
       ('DOC_CT_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-CT', 'SUV', 0, 0),
       ('DOC_CT_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-CT', 'SUV', 0, 0),
       ('DOC_CT_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-CT', 'SUV', 0, 0),
       ('DOC_CT_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-CT', 'SUV', 0, 0),
       ('DOC_CT_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-CT', 'SUV', 0, 0),
       ('DOC_DL_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-DL', 'BIKE', 0, 0),
       ('DOC_DL_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-DL', 'BIKE', 0, 0),
       ('DOC_DL_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-DL', 'BIKE', 0, 0),
       ('DOC_DL_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-DL', 'BIKE', 0, 0),
       ('DOC_DL_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-DL', 'BIKE', 0, 0),
       ('DOC_DL_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-DL', 'CAR', 0, 0),
       ('DOC_DL_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-DL', 'CAR', 0, 0),
       ('DOC_DL_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-DL', 'CAR', 0, 0),
       ('DOC_DL_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'PollUTION Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-DL', 'CAR', 0, 0),
       ('DOC_DL_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-DL', 'CAR', 0, 0),
       ('DOC_DL_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-DL', 'SUV', 0, 0),
       ('DOC_DL_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-DL', 'SUV', 0, 0),
       ('DOC_DL_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-DL', 'SUV', 0, 0),
       ('DOC_DL_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-DL', 'SUV', 0, 0),
       ('DOC_DL_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-DL', 'SUV', 0, 0),
       ('DOC_DN_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-DN', 'BIKE', 0, 0),
       ('DOC_DN_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-DN', 'BIKE', 0, 0),
       ('DOC_DN_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-DN', 'BIKE', 0, 0),
       ('DOC_DN_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-DN', 'BIKE', 0, 0),
       ('DOC_DN_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-DN', 'BIKE', 0, 0),
       ('DOC_DN_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-DN', 'CAR', 0, 0),
       ('DOC_DN_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-DN', 'CAR', 0, 0),
       ('DOC_DN_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-DN', 'CAR', 0, 0),
       ('DOC_DN_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-DN', 'CAR', 0, 0),
       ('DOC_DN_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-DN', 'CAR', 0, 0),
       ('DOC_DN_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-DN', 'SUV', 0, 0),
       ('DOC_DN_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-DN', 'SUV', 0, 0),
       ('DOC_DN_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-DN', 'SUV', 0, 0),
       ('DOC_DN_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-DN', 'SUV', 0, 0),
       ('DOC_DN_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-DN', 'SUV', 0, 0),
       ('DOC_GA_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-GA', 'BIKE', 0, 0),
       ('DOC_GA_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-GA', 'BIKE', 0, 0),
       ('DOC_GA_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-GA', 'BIKE', 0, 0),
       ('DOC_GA_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-GA', 'BIKE', 0, 0),
       ('DOC_GA_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-GA', 'BIKE', 0, 0),
       ('DOC_GA_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-GA', 'CAR', 0, 0),
       ('DOC_GA_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-GA', 'CAR', 0, 0),
       ('DOC_GA_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-GA', 'CAR', 0, 0),
       ('DOC_GA_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-GA', 'CAR', 0, 0),
       ('DOC_GA_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-GA', 'CAR', 0, 0),
       ('DOC_GA_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-GA', 'SUV', 0, 0),
       ('DOC_GA_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-GA', 'SUV', 0, 0),
       ('DOC_GA_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-GA', 'SUV', 0, 0),
       ('DOC_GA_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-GA', 'SUV', 0, 0),
       ('DOC_GA_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-GA', 'SUV', 0, 0),
       ('DOC_GJ_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-GJ', 'BIKE', 0, 0),
       ('DOC_GJ_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-GJ', 'BIKE', 0, 0),
       ('DOC_GJ_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-GJ', 'BIKE', 0, 0),
       ('DOC_GJ_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-GJ', 'BIKE', 0, 0),
       ('DOC_GJ_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-GJ', 'BIKE', 0, 0),
       ('DOC_GJ_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-GJ', 'CAR', 0, 0),
       ('DOC_GJ_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-GJ', 'CAR', 0, 0),
       ('DOC_GJ_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-GJ', 'CAR', 0, 0),
       ('DOC_GJ_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-GJ', 'CAR', 0, 0),
       ('DOC_GJ_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-GJ', 'CAR', 0, 0),
       ('DOC_GJ_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-GJ', 'SUV', 0, 0),
       ('DOC_GJ_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-GJ', 'SUV', 0, 0),
       ('DOC_GJ_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-GJ', 'SUV', 0, 0),
       ('DOC_GJ_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-GJ', 'SUV', 0, 0),
       ('DOC_GJ_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-GJ', 'SUV', 0, 0),
       ('DOC_HP_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-HP', 'BIKE', 0, 0),
       ('DOC_HP_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-HP', 'BIKE', 0, 0),
       ('DOC_HP_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-HP', 'BIKE', 0, 0),
       ('DOC_HP_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-HP', 'BIKE', 0, 0),
       ('DOC_HP_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-HP', 'BIKE', 0, 0),
       ('DOC_HP_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-HP', 'CAR', 0, 0),
       ('DOC_HP_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-HP', 'CAR', 0, 0),
       ('DOC_HP_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-HP', 'CAR', 0, 0),
       ('DOC_HP_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-HP', 'CAR', 0, 0),
       ('DOC_HP_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-HP', 'CAR', 0, 0),
       ('DOC_HP_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-HP', 'SUV', 0, 0),
       ('DOC_HP_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-HP', 'SUV', 0, 0),
       ('DOC_HP_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-HP', 'SUV', 0, 0),
       ('DOC_HP_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-HP', 'SUV', 0, 0),
       ('DOC_HP_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-HP', 'SUV', 0, 0),
       ('DOC_HR_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-HR', 'BIKE', 0, 0),
       ('DOC_HR_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-HR', 'BIKE', 0, 0),
       ('DOC_HR_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-HR', 'BIKE', 0, 0),
       ('DOC_HR_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-HR', 'BIKE', 0, 0),
       ('DOC_HR_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-HR', 'BIKE', 0, 0),
       ('DOC_HR_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-HR', 'CAR', 0, 0),
       ('DOC_HR_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-HR', 'CAR', 0, 0),
       ('DOC_HR_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-HR', 'CAR', 0, 0),
       ('DOC_HR_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-HR', 'CAR', 0, 0),
       ('DOC_HR_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-HR', 'CAR', 0, 0),
       ('DOC_HR_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-HR', 'SUV', 0, 0),
       ('DOC_HR_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-HR', 'SUV', 0, 0),
       ('DOC_HR_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-HR', 'SUV', 0, 0),
       ('DOC_HR_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-HR', 'SUV', 0, 0),
       ('DOC_HR_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-HR', 'SUV', 0, 0),
       ('DOC_JH_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-JH', 'BIKE', 0, 0),
       ('DOC_JH_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-JH', 'BIKE', 0, 0),
       ('DOC_JH_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-JH', 'BIKE', 0, 0),
       ('DOC_JH_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-JH', 'BIKE', 0, 0),
       ('DOC_JH_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-JH', 'BIKE', 0, 0),
       ('DOC_JH_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-JH', 'CAR', 0, 0),
       ('DOC_JH_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-JH', 'CAR', 0, 0),
       ('DOC_JH_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-JH', 'CAR', 0, 0),
       ('DOC_JH_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-JH', 'CAR', 0, 0),
       ('DOC_JH_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-JH', 'CAR', 0, 0),
       ('DOC_JH_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-JH', 'SUV', 0, 0),
       ('DOC_JH_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-JH', 'SUV', 0, 0),
       ('DOC_JH_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-JH', 'SUV', 0, 0),
       ('DOC_JH_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-JH', 'SUV', 0, 0),
       ('DOC_JH_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-JH', 'SUV', 0, 0),
       ('DOC_JK_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-JK', 'BIKE', 0, 0),
       ('DOC_JK_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-JK', 'BIKE', 0, 0),
       ('DOC_JK_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-JK', 'BIKE', 0, 0),
       ('DOC_JK_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-JK', 'BIKE', 0, 0),
       ('DOC_JK_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-JK', 'BIKE', 0, 0),
       ('DOC_JK_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-JK', 'CAR', 0, 0),
       ('DOC_JK_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-JK', 'CAR', 0, 0),
       ('DOC_JK_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-JK', 'CAR', 0, 0),
       ('DOC_JK_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-JK', 'CAR', 0, 0),
       ('DOC_JK_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-JK', 'CAR', 0, 0),
       ('DOC_JK_CAR_INNER_LINE_PERMIT___LOC_ADJACENT_AREAS_J_0901', 'Inner Line Permit - LOC/Adjacent Areas (J&K)', 'STATE_SPECIFIC', 'IN_STATE', 'IN-JK', 'CAR', 0, 0),
       ('DOC_JK_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-JK', 'SUV', 0, 0),
       ('DOC_JK_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-JK', 'SUV', 0, 0),
       ('DOC_JK_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-JK', 'SUV', 0, 0),
       ('DOC_JK_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-JK', 'SUV', 0, 0),
       ('DOC_JK_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-JK', 'SUV', 0, 0),
       ('DOC_KA_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-KA', 'BIKE', 0, 0),
       ('DOC_KA_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-KA', 'BIKE', 0, 0),
       ('DOC_KA_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-KA', 'BIKE', 0, 0),
       ('DOC_KA_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-KA', 'BIKE', 0, 0),
       ('DOC_KA_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-KA', 'BIKE', 0, 0),
       ('DOC_KA_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-KA', 'CAR', 0, 0),
       ('DOC_KA_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-KA', 'CAR', 0, 0),
       ('DOC_KA_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-KA', 'CAR', 0, 0),
       ('DOC_KA_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-KA', 'CAR', 0, 0),
       ('DOC_KA_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-KA', 'CAR', 0, 0),
       ('DOC_KA_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-KA', 'SUV', 0, 0),
       ('DOC_KA_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-KA', 'SUV', 0, 0),
       ('DOC_KA_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-KA', 'SUV', 0, 0),
       ('DOC_KA_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-KA', 'SUV', 0, 0),
       ('DOC_KA_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-KA', 'SUV', 0, 0),
       ('DOC_KL_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-KL', 'BIKE', 0, 0),
       ('DOC_KL_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-KL', 'BIKE', 0, 0),
       ('DOC_KL_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-KL', 'BIKE', 0, 0),
       ('DOC_KL_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-KL', 'BIKE', 0, 0),
       ('DOC_KL_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-KL', 'BIKE', 0, 0),
       ('DOC_KL_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-KL', 'CAR', 0, 0),
       ('DOC_KL_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-KL', 'CAR', 0, 0),
       ('DOC_KL_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-KL', 'CAR', 0, 0),
       ('DOC_KL_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-KL', 'CAR', 0, 0),
       ('DOC_KL_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-KL', 'CAR', 0, 0),
       ('DOC_KL_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-KL', 'SUV', 0, 0),
       ('DOC_KL_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-KL', 'SUV', 0, 0),
       ('DOC_KL_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-KL', 'SUV', 0, 0),
       ('DOC_KL_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-KL', 'SUV', 0, 0),
       ('DOC_KL_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-KL', 'SUV', 0, 0),
       ('DOC_MH_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-MH', 'BIKE', 0, 0),
       ('DOC_MH_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-MH', 'BIKE', 0, 0),
       ('DOC_MH_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-MH', 'BIKE', 0, 0),
       ('DOC_MH_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-MH', 'BIKE', 0, 0),
       ('DOC_MH_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-MH', 'BIKE', 0, 0),
       ('DOC_MH_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-MH', 'CAR', 0, 0),
       ('DOC_MH_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-MH', 'CAR', 0, 0),
       ('DOC_MH_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-MH', 'CAR', 0, 0),
       ('DOC_MH_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-MH', 'CAR', 0, 0),
       ('DOC_MH_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-MH', 'CAR', 0, 0),
       ('DOC_MH_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-MH', 'SUV', 0, 0),
       ('DOC_MH_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-MH', 'SUV', 0, 0),
       ('DOC_MH_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-MH', 'SUV', 0, 0),
       ('DOC_MH_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-MH', 'SUV', 0, 0),
       ('DOC_MH_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-MH', 'SUV', 0, 0),
       ('DOC_ML_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-ML', 'BIKE', 0, 0),
       ('DOC_ML_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-ML', 'BIKE', 0, 0),
       ('DOC_ML_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-ML', 'BIKE', 0, 0),
       ('DOC_ML_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-ML', 'BIKE', 0, 0),
       ('DOC_ML_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-ML', 'BIKE', 0, 0),
       ('DOC_ML_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-ML', 'CAR', 0, 0),
       ('DOC_ML_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-ML', 'CAR', 0, 0),
       ('DOC_ML_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-ML', 'CAR', 0, 0),
       ('DOC_ML_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-ML', 'CAR', 0, 0),
       ('DOC_ML_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-ML', 'CAR', 0, 0),
       ('DOC_ML_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-ML', 'SUV', 0, 0),
       ('DOC_ML_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-ML', 'SUV', 0, 0),
       ('DOC_ML_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-ML', 'SUV', 0, 0),
       ('DOC_ML_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-ML', 'SUV', 0, 0),
       ('DOC_ML_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-ML', 'SUV', 0, 0),
       ('DOC_MN_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-MN', 'BIKE', 0, 0),
       ('DOC_MN_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-MN', 'BIKE', 0, 0),
       ('DOC_MN_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-MN', 'BIKE', 0, 0),
       ('DOC_MN_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-MN', 'BIKE', 0, 0),
       ('DOC_MN_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-MN', 'BIKE', 0, 0),
       ('DOC_MN_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-MN', 'CAR', 0, 0),
       ('DOC_MN_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-MN', 'CAR', 0, 0),
       ('DOC_MN_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-MN', 'CAR', 0, 0),
       ('DOC_MN_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-MN', 'CAR', 0, 0),
       ('DOC_MN_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-MN', 'CAR', 0, 0),
       ('DOC_MN_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-MN', 'SUV', 0, 0),
       ('DOC_MN_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-MN', 'SUV', 0, 0),
       ('DOC_MN_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-MN', 'SUV', 0, 0),
       ('DOC_MN_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-MN', 'SUV', 0, 0),
       ('DOC_MN_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-MN', 'SUV', 0, 0),
       ('DOC_MP_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-MP', 'BIKE', 0, 0),
       ('DOC_MP_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-MP', 'BIKE', 0, 0),
       ('DOC_MP_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-MP', 'BIKE', 0, 0),
       ('DOC_MP_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-MP', 'BIKE', 0, 0),
       ('DOC_MP_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-MP', 'BIKE', 0, 0),
       ('DOC_MP_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-MP', 'CAR', 0, 0),
       ('DOC_MP_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-MP', 'CAR', 0, 0),
       ('DOC_MP_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-MP', 'CAR', 0, 0),
       ('DOC_MP_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-MP', 'CAR', 0, 0),
       ('DOC_MP_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-MP', 'CAR', 0, 0),
       ('DOC_MP_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-MP', 'SUV', 0, 0),
       ('DOC_MP_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-MP', 'SUV', 0, 0),
       ('DOC_MP_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-MP', 'SUV', 0, 0),
       ('DOC_MP_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-MP', 'SUV', 0, 0),
       ('DOC_MP_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-MP', 'SUV', 0, 0),
       ('DOC_MZ_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'BIKE', 0, 0),
       ('DOC_MZ_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'BIKE', 0, 0),
       ('DOC_MZ_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'BIKE', 0, 0),
       ('DOC_MZ_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'BIKE', 0, 0),
       ('DOC_MZ_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'BIKE', 0, 0),
       ('DOC_MZ_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'CAR', 0, 0),
       ('DOC_MZ_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'CAR', 0, 0),
       ('DOC_MZ_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'CAR', 0, 0),
       ('DOC_MZ_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'CAR', 0, 0),
       ('DOC_MZ_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'CAR', 0, 0),
       ('DOC_MZ_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'SUV', 0, 0),
       ('DOC_MZ_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'SUV', 0, 0),
       ('DOC_MZ_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'SUV', 0, 0),
       ('DOC_MZ_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'SUV', 0, 0),
       ('DOC_MZ_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-MZ', 'SUV', 0, 0),
       ('DOC_NL_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-NL', 'BIKE', 0, 0),
       ('DOC_NL_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-NL', 'BIKE', 0, 0),
       ('DOC_NL_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-NL', 'BIKE', 0, 0),
       ('DOC_NL_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-NL', 'BIKE', 0, 0),
       ('DOC_NL_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-NL', 'BIKE', 0, 0),
       ('DOC_NL_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-NL', 'CAR', 0, 0),
       ('DOC_NL_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-NL', 'CAR', 0, 0),
       ('DOC_NL_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-NL', 'CAR', 0, 0),
       ('DOC_NL_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-NL', 'CAR', 0, 0),
       ('DOC_NL_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-NL', 'CAR', 0, 0),
       ('DOC_NL_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-NL', 'SUV', 0, 0),
       ('DOC_NL_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-NL', 'SUV', 0, 0),
       ('DOC_NL_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-NL', 'SUV', 0, 0),
       ('DOC_NL_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-NL', 'SUV', 0, 0),
       ('DOC_NL_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-NL', 'SUV', 0, 0),
       ('DOC_OD_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-OD', 'BIKE', 0, 0),
       ('DOC_OD_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-OD', 'BIKE', 0, 0),
       ('DOC_OD_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-OD', 'BIKE', 0, 0),
       ('DOC_OD_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-OD', 'BIKE', 0, 0),
       ('DOC_OD_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-OD', 'BIKE', 0, 0),
       ('DOC_OD_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-OD', 'CAR', 0, 0),
       ('DOC_OD_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-OD', 'CAR', 0, 0),
       ('DOC_OD_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-OD', 'CAR', 0, 0),
       ('DOC_OD_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-OD', 'CAR', 0, 0),
       ('DOC_OD_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-OD', 'CAR', 0, 0),
       ('DOC_OD_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-OD', 'SUV', 0, 0),
       ('DOC_OD_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-OD', 'SUV', 0, 0),
       ('DOC_OD_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-OD', 'SUV', 0, 0),
       ('DOC_OD_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-OD', 'SUV', 0, 0),
       ('DOC_OD_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-OD', 'SUV', 0, 0),
       ('DOC_PB_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-PB', 'BIKE', 0, 0),
       ('DOC_PB_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_BH', 'IN-PB', 'BIKE', 0, 0),
       ('DOC_PB_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-PB', 'BIKE', 0, 0),
       ('DOC_PB_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-PB', 'BIKE', 0, 0),
       ('DOC_PB_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-PB', 'BIKE', 0, 0),
       ('DOC_PB_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-PB', 'CAR', 0, 0),
       ('DOC_PB_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-PB', 'CAR', 0, 0),
       ('DOC_PB_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-PB', 'CAR', 0, 0),
       ('DOC_PB_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-PB', 'CAR', 0, 0),
       ('DOC_PB_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-PB', 'CAR', 0, 0),
       ('DOC_PB_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_BH', 'IN-PB', 'SUV', 0, 0),
       ('DOC_PB_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_BH', 'IN-PB', 'SUV', 0, 0),
       ('DOC_PB_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_BH', 'IN-PB', 'SUV', 0, 0),
       ('DOC_PB_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_BH', 'IN-PB', 'SUV', 0, 0),
       ('DOC_PB_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_BH', 'IN-PB', 'SUV', 0, 0),
       ('DOC_PY_BIKE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'BIKE', 0, 0),
       ('DOC_PY_BIKE_DRIVING_LICENCE_MCWG___MCWOG_0002', 'Driving Licence (MCWG / MCWOG)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'BIKE', 0, 0),
       ('DOC_PY_BIKE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'BIKE', 0, 0),
       ('DOC_PY_BIKE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'BIKE', 0, 0),
       ('DOC_PY_BIKE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-PY', 'BIKE', 0, 0),
       ('DOC_PY_CAR_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'CAR', 0, 0),
       ('DOC_PY_CAR_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'CAR', 0, 0),
       ('DOC_PY_CAR_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'CAR', 0, 0),
       ('DOC_PY_CAR_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'CAR', 0, 0),
       ('DOC_PY_CAR_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-PY', 'CAR', 0, 0),
       ('DOC_PY_SUV_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'SUV', 0, 0),
       ('DOC_PY_SUV_DRIVING_LICENCE_LMV_0002', 'Driving Licence (LMV)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'SUV', 0, 0),
       ('DOC_PY_SUV_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'SUV', 0, 0),
       ('DOC_PY_SUV_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'SUV', 0, 0),
       ('DOC_PY_SUV_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-PY', 'SUV', 0, 0),
       ('DOC_PY_AMBULANCE_REGISTRATION_CERTIFICATE_RC_0001', 'Registration Certificate (RC)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_DRIVING_LICENCE_LMV___HMV_0002', 'Driving Licence (LMV / HMV)', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_VEHICLE_INSURANCE_CERTIFICATE_0003', 'Vehicle Insurance Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_POLLUTION_UNDER_CONTROL_PUC_CERTIFICATE_0004', 'Pollution Under Control (PUC) Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_ROAD_TAX_PAYMENT_RECEIPT_0005', 'Road Tax Payment Receipt', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_FITNESS_CERTIFICATE_0006', 'Fitness Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_AMBULANCE_PERMIT_FROM_STATE_HEALTH_AUTHO_0007', 'Ambulance Permit from State Health Authority', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_MEDICAL_EQUIPMENT_COMPLIANCE_CERTIFICATE_0008', 'Medical Equipment Compliance Certificate', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0),
       ('DOC_PY_AMBULANCE_FIRST_AID_AND_PARAMEDIC_CERTIFICATION_0009', 'First Aid and Paramedic Certification', 'MANDATORY', 'IN_STATE', 'IN-PY', 'AMBULANCE', 0, 0);